-- Oracle Database Creation and Seeding Scripts

-- Create Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(255),
    is_ldap NUMBER(1) DEFAULT 0,
    is_locked NUMBER(1) DEFAULT 0,
    is_enabled NUMBER(1) DEFAULT 1,
    password_reset_required NUMBER(1) DEFAULT 0,
    mfa_enabled NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Roles Table
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) UNIQUE NOT NULL
);

-- User-Roles Join Table
CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Create Phases Table
CREATE TABLE phases (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_number NUMBER UNIQUE NOT NULL,
    name VARCHAR2(100) NOT NULL
);

-- Create Document Deliverables Metadata Table
CREATE TABLE document_deliverables (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id VARCHAR2(50) UNIQUE NOT NULL, -- e.g. P001, P002
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    version VARCHAR2(20) DEFAULT '1.0',
    doc_code VARCHAR2(100),
    phase_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_phase FOREIGN KEY (phase_id) REFERENCES phases(id) ON DELETE CASCADE
);

-- Create Documents Processing Status and Submission Table
CREATE TABLE document_submissions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_deliverable_id NUMBER,
    app_code VARCHAR2(3) NOT NULL, -- 3-character application code e.g. APP
    file_name VARCHAR2(255) NOT NULL,
    file_path VARCHAR2(512),
    status VARCHAR2(50) DEFAULT 'PENDING_APPROVAL', -- PENDING_APPROVAL, APPROVED, REJECTED
    maker_username VARCHAR2(100) NOT NULL,
    checker_username VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    CONSTRAINT fk_doc_del FOREIGN KEY (doc_deliverable_id) REFERENCES document_deliverables(id) ON DELETE SET NULL
);

-- INSERT SEED DATA FOR ROLES
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_MAKER');
INSERT INTO roles (name) VALUES ('ROLE_CHECKER');

-- INSERT DEFAULT USERS
INSERT INTO users (username, password, email, is_ldap, is_locked, is_enabled)
VALUES ('admin', '$2a$12$R6lSgS9p53N.gshdImsaKOfO2Z1vS7D/Esh4vXwzK0W6T/K18W93i', 'admin@cth.com', 0, 0, 1);

INSERT INTO users (username, password, email, is_ldap, is_locked, is_enabled)
VALUES ('maker', '$2a$12$R6lSgS9p53N.gshdImsaKOfO2Z1vS7D/Esh4vXwzK0W6T/K18W93i', 'maker@cth.com', 0, 0, 1);

INSERT INTO users (username, password, email, is_ldap, is_locked, is_enabled)
VALUES ('checker', '$2a$12$R6lSgS9p53N.gshdImsaKOfO2Z1vS7D/Esh4vXwzK0W6T/K18W93i', 'checker@cth.com', 0, 0, 1);

-- SEED THE 7 SDLC PHASES
INSERT INTO phases (phase_number, name) VALUES (1, 'Prioritisation');
INSERT INTO phases (phase_number, name) VALUES (2, 'Pre-project');
INSERT INTO phases (phase_number, name) VALUES (3, 'Analysis');
INSERT INTO phases (phase_number, name) VALUES (4, 'Design');
INSERT INTO phases (phase_number, name) VALUES (5, 'Testing');
INSERT INTO phases (phase_number, name) VALUES (6, 'Execution / SIT / UAT');
INSERT INTO phases (phase_number, name) VALUES (7, 'Deployment');
